Controllers/LyThuyetController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Text.Json.Serialization;
using System.Text.Json;
using DemoGPLX.Models;
using Newtonsoft.Json;
using apigplx.ModelVM;

namespace DemoGPLX.Controllers
{
    public class LyThuyetController : Controller
    {
        JsonSerializerOptions opt = new JsonSerializerOptions()
        {
            WriteIndented = true,
            ReferenceHandler = ReferenceHandler.Preserve
        };

        CookieOptions options = new CookieOptions() { Expires = DateTime.Now.AddDays(1) };
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Hoc()
        {
            if (HttpContext.Request.Cookies["DataUserGPLX"] == null)
            {
                return RedirectToAction("ChonHang");
            }
            DataUser user = JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]);

            ViewBag.Cookies = user.Id;
            return View();
        }

        public IActionResult Thi()
        {
            if (HttpContext.Request.Cookies["DataUserGPLX"] == null)
            {
                return RedirectToAction("ChonHang");
            }
            DataUser user = JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]);
            ViewBag.Cookies = user.Id;
            ViewBag.setTest = true;
            ViewBag.time = new DbGplxContext().Hangs.Where(e => e.IdHang == int.Parse(user.Id)).FirstOrDefault().Thoigianthi;
            return View();
        }

        public IActionResult CauHaySai()
        {
            DataUser user = null;
            try
            {
                user = JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]);
            }
            catch (Exception ex)
            { Console.WriteLine(ex.Message); }

            if (user == null)
                return RedirectToAction("ChonHang");
            ViewBag.data = user;
            return View(user);

        }

        public IActionResult XoaDuLieuCauSai()
        {
            DataUser data = JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]);
            data.CauSais = new List<int>();
            HttpContext.Response.Cookies.Append("DataUserGPLX", JsonConvert.SerializeObject(data), options);
            return RedirectToAction("CauHaySai");
        }

        public IActionResult ChonHang()
        {
            ViewBag.hang = QuestionUtil.GetAllHang();
            return View(ViewBag.hang);
        }

        public IActionResult ChonHangThi(string id)
        {
            HttpContext.Response.Cookies.Delete("DataUserGPLX");
            DataUser data = new DataUser();
            data.Id = id;
            HttpContext.Response.Cookies.Append("DataUserGPLX", JsonConvert.SerializeObject(data), options);
            return RedirectToAction("Hoc");
        }

       [HttpPost]
        public JsonResult LayCauHoi(int id)
        {
            List<Cau> data = new List<Cau>();
            data = QuestionUtil.GetDataWithID(id);
            return Json(data, opt);
        }

        [HttpPost]
        public IActionResult ThemCau(int id, int index)
        {
            try
            {
                DataUser data = JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]);

                if (data.Caus.IndexOf(id) == -1)
                {
                    data.Caus.Add(id);
                    data.LuaChons.Add(index);
                }

                // Update user data
                HttpContext.Response.Cookies.Append("DataUserGPLX", JsonConvert.SerializeObject(data), options);

                // Optionally, return the updated data as JSON
                return Json(data);
            }
            catch (Exception )
            {
                // Handle exceptions appropriately
                return BadRequest("An error occurred while updating user data.");
            }
        }

        [HttpPost]
        public IActionResult ThemCauSai(int id)
        {
            try
            {
                DataUser data = JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]);

                if (data.CauSais.IndexOf(id) == -1)
                    data.CauSais.Add(id);
                // Update user data
                HttpContext.Response.Cookies.Append("DataUserGPLX", JsonConvert.SerializeObject(data));

                // Optionally, return the updated data as JSON
                return Json(data);
            }
            catch (Exception ex)
            {
                // Handle exceptions appropriately
                return BadRequest("An error occurred while updating user data.");
            }
        }

        public IActionResult LayCauSai()
        {
            if (HttpContext.Request.Cookies["DataUserGPLX"] == null)
            {
                return RedirectToAction("ChonHang");
            }
            DataUser user = JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]);
            List<Cau> lsCauHaySai = new List<Cau>();
            foreach (int i in user.CauSais)
            {
                lsCauHaySai.Add(QuestionUtil.GetQuestionWithoutImage(i));
            }
            return Json(lsCauHaySai, opt);
        }

        [HttpPost]
        public IActionResult LayDeThiMoi(int id)
        {
            var questions = QuestionUtil.CreateNewTest(id);

            var random = new Random();
            questions = questions.OrderBy(x => random.Next()).ToList();

            return Json(questions, opt);
        }

        [HttpPost]
        public IActionResult LayCauDaLam()
        {
            List<List<int>> ls = new List<List<int>>() {
                new List<int>(JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]).Caus),
                new List<int>(JsonConvert.DeserializeObject<DataUser>(HttpContext.Request.Cookies["DataUserGPLX"]).LuaChons)
            };


            return Json(ls);
        }



        [HttpPost]
        public IActionResult LayHinhCauHoi(int id)
        {
            return Json(QuestionUtil.GetImageQuestion(id));
        }


        public IActionResult SearchQuestion(string search, bool choose = false)
        {
            search = AppUtil.ToLowerCaseNonAccentVietnamese(search.ToLower());
            List<Cau> lsAllQues = QuestionUtil.GetAllQuestion();
            List<Cau> lsQues = new List<Cau>();
            if (!choose)
            {
                foreach (Cau c in lsAllQues)
                {
                    if (AppUtil.ToLowerCaseNonAccentVietnamese(c.Ttcaus.ElementAt(0).Cauhoi.ToLower()).Contains(search))
                    {
                        lsQues.Add(c);
                        continue;
                    }
                    else
                    {
                        foreach (Dapan dapan in c.Dapans)
                        {
                            if ((AppUtil.ToLowerCaseNonAccentVietnamese(dapan.Dapan1.ToLower()).Contains(search)))
                            {
                                lsQues.Add(c);
                                break;
                            }
                        }
                    }
                }
            }
            return Json(lsQues, opt);
        }
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var httpContext = HttpContextAccessor.HttpContext;
    var useGPLXCookie = httpContext.Request.Cookies["UserGplx"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - DemoGPLX</title>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@800&family=Noto+Sans+Linear+A&family=Oswald:wght@200;400&family=Roboto:wght@300;500&family=Silkscreen&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoGPLX.styles.css" asp-append-version="true" />
    <script src="./js/site.js"></script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GPLX_STU</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (useGPLXCookie == null)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="LyThuyet" asp-action="Hoc">Học lý thuyết</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="LyThuyet" asp-action="Thi">Thi thử</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="LyThuyet" asp-action="CauHaySai">Câu hay sai</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="LyThuyet" asp-action="Chonhang">Chọn hạng</a>
                            </li>
                        </ul>
                    }
                    else
                    {

                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="CauHoi" asp-action="Hanglaixe">Hạng</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="CauHoi" asp-action="Index">Câu hỏi</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="CauHoi" asp-action="Chuong">Chương</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-header" asp-area="" asp-controller="CauHoi" asp-action="Logout">Đăng xuất</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top text-muted">
        <div class="">
            &copy; 2023 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

                    